baseurl = "http://staging.hanbei.de/"
#languageCode = "en-us"
theme = "hanbei"

DefaultContentLanguage = "en"

[Languages.en]
    weight = 1
    title = "Florian Schulz - software and data engineer"
    me = "Florian Schulz - software and data engineer"
    slogan = "Evolving software to its full potential"


[Languages.de]
    weight = 2
    title = "Florian Schulz - software and data engineer"
    me = "Florian Schulz - software and data engineer"
    slogan = "Evolving software to its full potential"

[params]
  image = "/images/me.jpeg"
  mail = "contact@hanbei.de"
  linkedin = "https://de.linkedin.com/in/florian-schulz-580b3491"
  github = "https://github.com/hanbei"
  twitter = "https://twitter.com/flschlz"
  xing = "https://www.xing.com/profile/Florian_Schulz45"
