baseurl = "http://staging.hanbei.de/"
#languageCode = "en-us"
title = "My New Hugo Site"
theme = "hanbei"

DefaultContentLanguage = "en"

[Languages.en]
    weight = 1
    title = "Test (en)"
    me = "Florian Schulz - software and data engineer"
    slogan = "Software Systeme"


[Languages.de]
    weight = 2
    title = "Test (de)"
    me = "Florian Schulz - software and data engineer"
    slogan = "Software Systeme"

[params]
  image = "/images/me.jpeg"
  mail = "hanbei@hanbei.de"
  linkedin = "https://de.linkedin.com/in/florian-schulz-580b3491"
  github = "https://github.com/hanbei"
  twitter = "https://twitter.com/flschlz"
