baseurl = "http://staging.hanbei.de/"
#languageCode = "en-us"
title = "My New Hugo Site"
theme = "hanbei"

[params]
  image = "images/me.jpeg"
  me = "Florian Schulz - software and data engineer"
  slogan = "Evolving software systems to their full potential"

  mail = "hanbei@hanbei.de"
  linkedin = "https://de.linkedin.com/in/florian-schulz-580b3491"
  github = "https://github.com/hanbei"
  twitter = "https://twitter.com/flschlz"
