baseurl = "http://www.hanbei.de"
languageCode = "en-us"
title = "hanbei"
theme = "casper"

[params]
  githubName = "hanbei"
  #logo = "images/logo.png"
  cover = "images/cover.jpg"
  linkedinName = "florian-schulz-580b3491"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 0
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Legal Info"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 1
    identifier = "disclaimer"
    url = "disclaimer"

[social]
  # Link your social networking accouns to the side menu
  # by entering your username or ID.

  # SNS microblogging
  #twitter = "*"
  #facebook = "*"
  #googleplus = "*"
  #weibo = "*"

  # SNS photo/video sharing
  #instagram = "*"
  #flickr = "*"
  #pinterest = "*"
  #youtube = "*"
  #vimeo = "*"
  #vine = "*"
  #slideshare = "*"

  # SNS career oriented
  #linkedin = "*"
  #xing = "*"

  # SNS news
  #reddit = "*"
  #hackernews = "*"

  # Techie
  github = "hanbei"
  #bitbucket = "*"
  #stackoverflow = "*"
